development:
  hosts:
    - host: 'localhost'
      port: 9200
      user: 'elastic'
      password: '4*773l=za4IM=+nQKBh0'

production:
  hosts:
    - host: '<production-host>'
      port: 9200
      user: 'elastic'
      password: '4*773l=za4IM=+nQKBh0'
